config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :professors do
    collection do 
      get 'search'
    end
    resources :reviews
  end

  root 'professors#index'

end

app/models/professor.rb
class Professor < ActiveRecord::Base
	searchkick
	belongs_to :user
	has_many :reviews, dependent: :destroy
	has_attached_file :image, :styles => { :medium => "400x600>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	validates_presence_of :name, :title, :department

  	# def self.search(search)
  	# 	if search
  	# 		where("name = ? OR department = ?", search, search)
  	# 	else
  	# 		find(:all)
  	# 	end
  	# end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :professor
	belongs_to :user
	paginates_per 10
	validates_presence_of :rating, :classname, :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :professors
  has_many :reviews, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :admin?


  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def admin?
  	current_user.email == "rachel960122@hotmail.com"
  end

end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :department_list, only: [:new, :edit]
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :search, :show]
  before_filter :authorize, only: [:edit, :destroy]


  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all.order("name")
  end

  def search
    #@professors = Professor.search(params[:search])
    if params[:search]
      @professors = Professor.search(params[:search])
    else
      @professor = Professor.all.order("name")
    end
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @reviews = @professor.reviews.order("created_at DESC").page params[:page]
    if !@professor.reviews.blank?
      @avg_score = @professor.reviews.average(:rating).round(1)
    else
      @avg_score = 0
    end
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)
    @professor.user_id = current_user.id
    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

    def authorize
      unless admin?
        flash[:error] = "Unauthorized Access"
        redirect_to @professor
        false
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name, :title, :department, :link, :image)
    end

    def department_list
      @dept_list = ['Africana Studies', 'Anthropology', 'Arabic', 'Archaeology', 'Architecture',
        'Arts Program – Creative Writing', 'Arts Program – Dance', 'Arts Program – Fine Arts', 
        'Arts Program - Music', 'Arts Program - Theater', 'Astronomy', 'Biology',
        'Biochemistry & Molecular Biology', 'Chemistry', 'Child and Family Studies','Classics', 
        'Comparative Literature', 'Computer Science', 'East Asian Languages and Cultures', 'Economics', 
        'Education', 'English', 'Environmental Studies', 'Film Studies', 'French', 'Gender and Sexuality', 
        'Geology', 'German', 'Greek, Latin and Classical Studies', 'Growth and Structure of Cities',
        'Hebrew and Judaic Studies', 'History', 'History of Art', 'International Studies', 'Italian', 
        'Latin-American Studies', 'Linguistics', 'Mathematics', 'Mathematics & Statistics', 
        'Middle Eastern Studies', 'Philosophy','Physics','Political Science', 'Psychology', 'Religion',
        'Romance Languages', 'Russian', 'Social Work and Social Research', 'Sociology','Spanish'
      ]
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_professor
	before_action :set_review, except: [:new, :create]
	before_action :authenticate_user!
  before_filter :authorize, only: [:edit, :destroy]

  def new
  end

  def create
    @review = @professor.reviews.create(review_params)
    @review.user_id = current_user.id
    if @review.save
    	redirect_to @professor
    else
    	render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
  	if @review.update(review_params)
  		redirect_to @professor
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@review.destroy
  	redirect_to @professor
  end

  protected

    def authorize
      unless admin?
        flash[:error] = "Unauthorized Access"
        redirect_to professor_review_path(@professor, @review)
        false
      end
    end
 
  private

  	def set_review
  		@review = Review.find(params[:id])
  	end

  	def set_professor
  		@professor = Professor.find(params[:professor_id])
  	end

    def review_params
      params.require(:review).permit(:rating, :classname, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default", role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand", style: "padding-top: 16.5px; padding-right: 7px" do %>
        <img src="/assets/home3.ico", alt="owl" />
      <% end %>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if !user_signed_in? %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Create A New Professor", new_professor_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit my account", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <!-- <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <%= form_tag search_professors_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Enter name/department", class: "form-control" %>
          <%= submit_tag :search, name: nil, class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rate My Professor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert alert-info" %>
		<% end %>
		<%= yield %>
	</div>



</body>
</html>

app/views/professors/_form.html.erb
<%= form_for(@professor, :html => { :multipart => true }) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group", style="width: 30%">
    <%= f.label :name, "Name" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group", style="width: 30%">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :department, "Department" %><br>
    <%= f.select(:department, @dept_list) %>
  </div>

  <div class="form-group", style="width: 30%">
    <%= f.label :link, "Link to CV or personal website" %><br>
    <%= f.text_field :link, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Upload a profile picture" %><br>
    <%= f.file_field :image, class: "file-field" %>
  </div>

  <span class="actions">
    <%= f.submit class: "btn btn-success" %>
    <%= link_to 'Back', root_path, class: "btn btn-default" %>
  </span>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render 'form' %>

app/views/professors/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Your Favorite Bi-Co Professors Being Reviewed</h1>
    <p>Join us to set up profiles or write reviews for your professors!</p>
    <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div>
  <h2 class="featured">List of all Professors</h2>
</div>

<div class="row">
  <% @professors.each do |professor| %>
    <div class="col-sm-6 col-md-3">
      <div class="images">
        <%= link_to professor do %>
          <%= image_tag professor.image.url, size: "250x270" %>
        <% end %>
        <div class="image-description", vertical-align:"middle">
          <%= professor.name %><br>
          <%= professor.department %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render 'form' %>

app/views/professors/search.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Your Favorite Bi-Co Professors Being Reviewed</h1>
    <p>Join us to set up profiles or write reviews for your professors!</p>
    <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div>
  <h2 class="featured">Search Results</h2>
</div>

<div class="row">
  <% @professors.each do |professor| %>
    <div class="col-sm-6 col-md-3">
      <div class="images">
        <%= link_to professor do %>
          <%= image_tag professor.image.url, size: "250x270" %>
        <% end %>
        <div class="image-description">
          <%= professor.name %><br>
          <%= professor.department %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/professors/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-lg-4">
				<div align="center">
				    <%= image_tag @professor.image.url, class: "image-show" %>
				</div>
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td><strong>Name:</strong></td>
							<td><%= @professor.name %></td>
						</tr>

						<tr>
							<td><strong>Title:</strong></td>
							<td><%= @professor.title %></td>
						</tr>

						<tr>
							<td><strong>Department:</strong></td>
							<td><%= @professor.department %></td>
						</tr>

						<tr>
							<td><strong>Link:</strong></td>
							<td><%= link_to @professor.link, @professor.link %></td>
						</tr>
					</tbody>
				</table>
			</div>
				<div align="center">
					<div class="btn-group">
						<% if user_signed_in? %>
							<% if admin? or current_user == @professor.user %>
								<%= link_to "Edit", edit_professor_path(@professor), class: "btn btn-info" %>
								<%= link_to "Delete", @professor, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-info" %>
							<% end %>
						<% end %>
						<%= link_to 'Back', root_path, class: "btn btn-info" %>
					</div>

					<%= link_to "Write a review", new_professor_review_path(@professor), class: "btn btn-primary" %>
				</div>
			</div>

			<div class="col-lg-8">
				<div class="panel panel-info">
					<div class="panel-heading">
						<div>Reviews for <%= @professor.name %></div>
						<span style="font-size:50%; padding-right: 15px"><%= pluralize(@professor.reviews.count, "review") %></span>
						<span class="star-rating", data-score=<%= @avg_score %>>average rating: </span>
					</div>
				</div>
				<% if !@reviews.blank? %>
					<table class="table table-hover">
						<thead>
							<tr>
								<th>Rating</th>
								<th>Class</th>
								<th>Comment</th>
							</tr>
						</thead>
						<tbody>
							<% @reviews.each do |review| %>
								<tr>
									<td><div class="star-rating", data-score=<%= review.rating %>></div></td>
									<td><%= review.classname %></td>
									<td><%= truncate(review.comment, length: 40) %></td>
									<td>
										<%= link_to professor_review_path(@professor, review) do %>
											<img src="/assets/open.ico", alt="show", class="icon" />
										<% end %>
										<% if user_signed_in? %>
											<% if admin? or current_user == review.user %>
												<%= link_to edit_professor_review_path(@professor, review) do %>
													<img src="/assets/edit.ico", alt="edit", class="icon" />
												<% end %>
												<%= link_to professor_review_path(@professor, review), method: :delete, data: {confirm: 'Are you sure?'} do %>
													<img src="/assets/delete.ico", alt="delete", class="icon" />
												<% end %>
											<% end %>
										<% end %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
					<span align="center"><%= paginate @reviews %></span>
				<% else %>
					<div>
						<h4>No reviews just yet. Would you like to <%= link_to "add one", new_professor_review_path(@professor) %>?</h4>
					</div>
				<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<script>
	$('.star-rating').raty({
		readOnly: true,
		path: '/assets/',
		precision: true,
		score: function() {
			return $(this).attr('data-score');
		},
		hints: function() {
			return $(this).attr('data-score');
		}
	});
</script>

app/views/reviews/edit.html.erb
<h2>Edit Review</h2>

<%= form_for([@professor, @professor.reviews.build], url: professor_review_path(@professor, @review), method: :patch) do |f| %>
  <div class="form-group", style="width: 25%">
    <%= f.label :rating %><br>
    <div id="star-rating", data-score=<%= @review.rating %>></div>
  </div>
  <div class="form-group", style="width: 25%">
    <%= f.label :classname, "Class" %><br>
    <%= f.text_field :classname, class: "form-control", value: @review.classname %>
  </div>
  <div class="form-group", style="width: 40%">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control", style: "height: 180px", value: @review.comment %>
  </div>
  <div>
    <%= f.submit "Update Review", class: "btn btn-success" %>
    <%= link_to "Back", @professor, class: "btn btn-default" %>
  </div>
<% end %>

<script>
  $("#star-rating").raty({
  	half: true,
    path: "/assets/",
    score: function() {
    	return $(this).attr("data-score");
    },
    scoreName: "review[rating]"
  })
</script>

app/views/reviews/new.html.erb
<h2>New Review</h2>

<%= form_for([@professor, @professor.reviews.build]) do |f| %>

  <div class="form-group", style="width: 25%">
    <%= f.label :rating %><br>
    <div id="star-rating"></div>
  </div>
  <div class="form-group", style="width: 25%">
    <%= f.label :classname, "Class" %><br>
    <%= f.text_field :classname, class: "form-control" %>
  </div>
  <div class="form-group", style="width: 40%">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control", style: "height: 180px" %>
  </div>
  <div>
    <%= f.submit class: "btn btn-success" %>
    <%= link_to "Back", @professor, class: "btn btn-default" %>
  </div>
<% end %>

<script>
  $("#star-rating").raty({
    half: true,
    path: "/assets/",
    scoreName: "review[rating]"
  })
</script>

app/views/reviews/show.html.erb
<div class="col-lg-6">
	<div class="panel panel-default">
		<div class="panel-body">
			<div style="padding-bottom: 10px">
				<span><strong>Rating: </strong><span class="star-rating", data-score=<%= @review.rating %>, style="padding-right: 15px"> </span></span>
				<span><strong>Class: </strong><%= @review.classname %></span>
			</div>
			<%= @review.comment %>
			<div style="padding-top: 7px"><i><%= @review.created_at %></i></div>
		</div>

		<div class="panel-footer">
			<div class="btn-group">
				<% if user_signed_in? %>
					<% if admin? or current_user == @review.user %>
						<%= link_to 'Edit', edit_professor_review_path(@professor, @review), class: "btn btn-info" %>
						<%= link_to 'Delete', professor_review_path(@professor, @review), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-info" %>
					<% end %>
				<% end %>
				<%= link_to 'Back', @professor, class: "btn btn-info" %>
			</div>
		</div>
	</div>
</div>

<script>
	$(".star-rating").raty({
		readOnly: true,
		path: "/assets/",
		precision: true,
		score: function() {
			return $(this).attr("data-score");
		},
		hints: function() {
			return $(this).attr("data-score");
		}
	})
</script>


